baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "tbrugz.github.io"
theme = "hugo-lithium-theme"
# theme = "hugo-type-theme"
# Enable comments by entering your Disqus shortname
# disqusShortname = ""
# Add your tracking code to enable Google Analytics
# googleAnalytics = ""
# Posts per page
paginate = 10
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
	#post = "/:year/:month/:day/:slug/"
	post = "/:year/:slug/"

#[[menu.main]]
#	name = "About"
#	url = "/about/"
[[menu.main]]
	name = "Bitbucket"
	url = "https://bitbucket.org/tbrugz"
[[menu.main]]
	name = "GitHub"
	url = "https://github.com/tbrugz"
[[menu.main]]
	name = "Twitter"
	url = "https://twitter.com/tbrugz"

[params]
	author = "Telmo Brugnara"
	description = "Add a description of your website"
	# The keywords will be added as a meta tag. Delimit them with a comma.
	keywords = ""
	# Either show custom avatar on the top
	# left by adding the filename in below
	# avatar = "img/avatar.png"
	# or use Gravatar by adding your email address to generate a unique avatar
	gravatar = "tbrugz@gmail.com"

	# headerText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.<br><br>Remove all header text in **config.toml** to disable this feature."
	# To add a header background to the main site, save your image under static/img/.
	# If now image path is provided, a orange background will be shown instead.
	headerImage = ""
	# copyright = "Powered by [Hugo](//gohugo.io/) with the [Type Theme](//github.com/digitalcraftsman/hugo-type-theme)"
	# copyright = "Released under the MIT license<br>Powered by [Hugo](//gohugo.io/) with the [Type Theme](//github.com/digitalcraftsman/hugo-type-theme)"

	# options for highlight.js (version, additional languages, and theme)
	highlightjsVersion = "9.9.0"
	highlightjsLang = ["r", "yaml"]
	highlightjsTheme = "github"

	[params.logo]
		url = "logo.png"
		width = 50
		height = 50
		alt = "Logo"

	[params.social]
		# Insert your accout name and the icon will be shown in the right menu
		rss = true
		homepage = true
		email = "tbrugz@gmail.com"
		behance = ""
		bitbucket  ="tbrugz"
		dribbble = ""
		facebook = ""
		flickr = ""
		github = "tbrugz"
		googleplus = ""
		instagram = ""
		linkedin = ""
		pinterest = ""
		reddit = ""
		soundcloud = ""
		stackexchange = ""
		steam = ""
		tumblr = ""
		twitter = "tbrugz"
		wordpress = ""
		youtube = ""
